### ISSUE TITLE
Optionally use tee instead of capture

### ISSUE THREAD

**Issue by perlpunk** [briandfoy/test-output#16]
We're using Test::Output and often have the situation that we print debugging statements when working on a test.
To see the actual output, we have to change `stderr_like` to `stderr_from`, save it into a variable, add a `like` statement and diag the output.
It would be helpful if Test::Output could use Capture::Tiny's `tee` function on request, for example via an environment variable.
If you think this could be useful as well, I would try to make a PR.

**Comment by briandfoy** [comment]
I'm skeptical, but I'll take a look. Perhaps you could come up with an interface example first. It seems that you'd end up at the same thing since you still need a way to get at the returned output.

**Comment by perlpunk** [comment]
I added a draft:
* #17

It is still capturing the output, so the test keeps working, it's simply printing the output additionally.

**Comment by Leont** [comment]
My experience is that you want a test to be quiet when it succeeds but verbose when it fails. Making it conditional on that makes more sense to me than making it depend on an environmental variable.

Also, this **MUST NOT** write arbitrary data to stdout. Otherwise, if the output contains valid TAP like an `ok` line, the TAP harness will get mightily confused. Writing to stderr or commenting it like `note` does are both valid options though.

**Comment by perlpunk** [comment]
For me it would also be helpful in the succeeding case. I start extending a test and first just want to see what the output actually looks like.
We are calling scripts in our tests that can output quite a lot.

Printing the captured output via `note` is something I also would like. I just thought using the existing `tee_` functions would be the easiest.

**Comment by briandfoy** [comment]
I agree with Leon here. You don't get to write to standard output in Test::Output. I was envisioning something where you were going to give back the output as variables that the test program could then access. At that point your test program could decide what to do with those values.

I see a few problems with this idea:

* By using an environment variable, you get it for everything or nothing. That is, unless you change the environment for a particular test, which means you are editing the test source to make the change. I don't see a good way to add such a feature without making every test spew a bunch of stuff (and I think that's even worse).
* There's already a way to do this with `stdout_from` and its friends, then running the tests that you like. You get the output, which you have to get in some way anyway, and then you can run a test and decide what to do. I haven't thought up something that's simpler than that.
* It's easy to make your own subroutines that combine tests in any way that you like to do exactly what you want to do. You can then use that subroutine anywhere you want to do that. I typically wrap all that in a subtest.
* This is some widely-used code, and I think there has to be a really good reason to change it. The change would have to make things significantly easier for users, or much easier to maintain.

I think you have to come up with something simpler than this:

```
my $output = stdout_from {...};
like $output, $patttern or diag( $output );
````

If this is what you want to do, you can do it now. I'd just leave it like that instead of changing it back to `stdout_like`. It seems to me that any way you do it, you end up with at least two lines of code.

In these cases I tend to do something like this, where even in failure I can decide how much I what to spew out:

```
my $output = stdout_from {...};
like $output, $patttern;
diag( $output ) if $ENV{TEST_VERBOSE}; # or whatever var you want
```

**Comment by perlpunk** [comment]
Fair enough, it's your module :)

I already explained my reasons and that I'm annoyed by having to edit the test to change from a `stdout_like` to `my $out = stdout_from ...; diag $out; like ...;`.

> By using an environment variable, you get it for everything or nothing.

Yes, that's what I often want.

> That is, unless you change the environment for a particular test, which means you are editing the test source to make the change.

Yes, it's just a simple line I can easily add and remove.

I can also force the regex to fail to get Test::More giving me a complaint that it doesn't match along with the output.

It's just that my PR would work perfect for my daily workflow, but if I'm the only one I have to write my own module.

**Comment by briandfoy** [comment]
It's not that it's my module, my rules. I do have stewardship of this module, but I didn't create it. Modules that are widely used need more careful stewardship. This is a pretty big change that affects a lot of the tests, so there are going to be questions.
